### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by Moini** [drphonon/Inkscape_LivingHinge#2]
Hi drphonon,

it seems that you accidentally removed all mention of the original authors of the extension, see original source file here:
http://www.reidb.net/code/LivingHinge.py

Would you please add the copyright notice back to comply with the extension's licence?

**Comment by drphonon** [comment]
i didn't use their code. I was not even aware of its existence.

**Comment by drphonon** [comment]
The code here is all mine.

**Comment by Moini** [comment]
You're right, sorry for not checking more thoroughly! 
I got mislead by the first function in the file having the exact same name - after that, I didn't read on.... :-/ The rest is different, though. Maybe you two got that from the same source...
