### ISSUE TITLE
Shell script issue

### ISSUE THREAD

**Issue by Moini** [drphonon/Inkscape_LivingHinge#3]
The script coming with the extension copies it into a folder that will be overwritten on updating Inkscape. The correct location for user extensions, that are supposed to be kept, and backed up etc.,  is ~/.config/inkscape/extensions for Linux systems (and something else for Windows and OS X).

**Comment by Moini** [comment]
Why did you close this without any comment, Mark? It's relevant, even if the copyright thing wasn't.

**Comment by drphonon** [comment]
Sorry. I made the changes to the script file. I don't use github often so I'm not up on the ettiqute.

**Comment by Moini** [comment]
I broke it, too, by not being diligent enough... Thank you for making the change!

Would you like to upload the extension to inkscape.org, into the Addons section, to make it more visible?

Info links:
List of currently uploaded extensions: https://inkscape.org/en/gallery/=extension/
HowTo: https://inkscape.org/en/develop/extensions/#sharing-your-extension
